### ISSUE TITLE
Empty Added file entries showing up in diff

### ISSUE THREAD

**Issue by michallepicki** [hexpm/diff#29]
Hi! The project looks great :)

On this page the fourth and fifth files are empty files with no file path or name or content, I'm confused - maybe it's a bug? https://diff.hex.pm/diff/ex_doc/0.21.1..0.21.2

**Comment by joladev** [comment]
You're right! It's an inconsistency in how diffs are parsed, I made a PR here with a potential fix https://github.com/mononym/git_diff/pull/6

Alternatively, we handle it as a special case ourselves, but ideally, it's fixed in the parsing lib.

**Comment by wojtekmach** [comment]
@joladev I verified the fix, good catch! Feel free to add it to our git_diff fork.
