### ISSUE TITLE
Handle search maxlength on the backend as well

### ISSUE THREAD

**Issue by michallepicki** [hexpm/diff#32]
Text input's `maxlength` attribute is supported on most browsers but on most Android browsers, the additional characters get removed after input focus is lost (see https://caniuse.com/#search=maxleng ). This leads to "funny" behavior when typing very long strings, but really this is just a too-easy way to put unnecessarily load onto the server.

**Comment by joladev** [comment]
Very long strings are not a huge issue here, it just does a lookup in an ETS table. But what is "funny" behavior? If it's breaking the app in some way it would be really useful to know!

**Comment by michallepicki** [comment]
Just unresponsiveness after typing a long query:
![Uploading Screen_Recording_20200121-181423_1.gif…]()
Clearing it doesn't immediately help as well, one has to refresh or wait a minute or two:

![Screen_Recording_20200121-181423_2](https://user-images.githubusercontent.com/4972756/72827242-b5ae5800-3c7a-11ea-9700-6da018635136.gif)

This is not a big issue but I think can be easily addressed :)

**Comment by michallepicki** [comment]
> it just does a lookup in an ETS table

It also computes jaro distance to all package names, right? This is the "slowest" part if I had to guess

**Comment by joladev** [comment]
@michallepicki yeah that could be it, I'll experiment a bit. I noticed it actually gets a little bit sluggish even at the 30th character on my laptop.

**Comment by ericmj** [comment]
maxlength is removed on the frontend so it's no longer needed on the backend :).
