### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by pluralmonad** [hexpm/diff#35]
Attempting to diff tzdata version 0.5.16 and 0.5.19 results in 500 response.

https://diff.hex.pm/diff/tzdata/0.5.16..0.5.19

Here is a request id for one of them.

Fev5YjVmBE18FDIAAD-h

**Comment by joladev** [comment]
Hey, thanks for this report! I made a PR to improve the error message.

I'll take a look at the library we use for parsing diffs and why it's failing on that one.

**Comment by ericmj** [comment]
This error is fixed on git_diff master. With @joladev's I think we can close this. Thanks for the report!
