### ISSUE TITLE
Suggestions not clickable in iOS (safari)

### ISSUE THREAD

**Issue by vermaxik** [hexpm/diff#37]
There is a famous issue in `phoenix_live_view` and `phx-click` event on [iOS Safari](https://github.com/phoenixframework/phoenix_live_view/issues?q=is%3Aissue+ios+is%3Aclosed)

<img src="https://user-images.githubusercontent.com/2705386/72882813-8859bc80-3d03-11ea-990f-2f2fbb3ce250.gif" width="300" >

Platform: iOS
Versions: All
Browser: Safari

I'll prepare MR to fix it.

**Comment by joladev** [comment]
Fixed in #38
