### ISSUE TITLE
Package name input maxlength is maybe too short

### ISSUE THREAD

**Issue by michaeljones** [hexpm/diff#55]
It lead to a slightly confusing experience when trying to get the diff for `telemetry_metrics_prometheus_core` which is 33 characters and so longer than then current 30 character limit.

You can still select the correct package name from the suggestions at which point the full name appears in the input field which is probably good but confusing that it can be displayed but not typed. 

I don't know what purpose the `maxlength` is serving so I don't know the trade-offs. Maybe this is for the best.

Thanks for the great project though. I feel super diligent & responsible when I look through package diffs :) I haven't had that experience in other development environments.

**Comment by ericmj** [comment]
We should not have a max length on diff.hex.pm since hex.pm does not have a max length (so far). Can you send a PR that removes it? Thank you!
