### ISSUE TITLE
Add /diff/:package/:version page

### ISSUE THREAD

**Issue by wojtekmach** [hexpm/diff#75]
Currently we only support `/diff/:package/:version1..:version2`, that is, we create the diff between two versions.

This new endpoint would compare the given version against the immediately preceding version which we'd grab by using Hex HTTP API.

**Comment by ericmj** [comment]
Another option is to have a link that lands you on https://diff.hex.pm/ with package name and "to" version already filled in. So you can just select the "from" version (default is the preceding version) and then go.

**Comment by ericmj** [comment]
What about `https://diff.hex.pm/?package=...&to=...` in that case?

**Comment by wojtekmach** [comment]
Good call. Closing in favour of #76.
