### ISSUE TITLE
UX improvements proposal

### ISSUE THREAD

**Issue by thbar** [hexpm/diff#77]
I've been using `diff.hex.pm` when working with batch upgrades (see http://gist.github.com/thbar/9a19e974818d0f828b3b6f8a0c1ace46 for instance).

When doing so, it is common to open many diff tabs (from the generated list of diff links e.g. at https://github.com/etalab/transport-site/pull/1910).

Once you have many tabs opened, I noticed that it is unclear which package you are seeing.

I believe the following changes could improve the experience quite a bit.

The following suggestions come from my experience using a similar tool for Ruby (https://my.diffend.io/gems/httparty/0.18.1/0.20.0):

1. Adding the name of the diff'ed package directly on top, at the right of the "hex diff" logo (example link https://diff.hex.pm/diff/aasm/0.1.0..0.2.0).

It would be nice to display the versions, too (from -> to):

<img width="298" alt="CleanShot 2021-11-10 at 14 46 47@2x" src="https://user-images.githubusercontent.com/10141/141124431-5de03410-82dc-4ffc-b350-420bdaccad0e.png">

2. Modifying the `title` HTML tag to display the name of the package first:

<img width="194" alt="CleanShot 2021-11-10 at 14 47 31@2x" src="https://user-images.githubusercontent.com/10141/141124552-d2742503-4c61-4da0-8e02-da07ab75a63b.png">

These are just suggestions, I'm curious to hear what you think about them!

**Comment by ericmj** [comment]
I think those are all really great suggestions. Let us know if you would like to work on them.

**Comment by thbar** [comment]
@ericmj workload is a bit heavy at the moment. I would be happy to tackle this at some point though, yes. You can either close or leave opened as you prefer, I will in all cases comment here if I work on it. Thanks for the feedback!
